// Code generated by file2byteslice. DO NOT EDIT.
// (gofmt is fine after generating)

package main

var chromaticaberration_go = []byte("// +build ignore\r\npackage main\r\n\r\nvar Time float\r\nvar Cursor vec2\r\n\r\nfunc Fragment(position vec4, texCoord vec2, color vec4) vec4 {\r\n\tcenter := vec2(320, 240)\r\n\tamount := normalize(center-Cursor).x / 100\r\n\tclr := vec3(0, 0, 0)\r\n\tclr.r = texture2At(vec2(texCoord.x+amount, texCoord.y)).r\r\n\tclr.g = texture2At(texCoord).g\r\n\tclr.b = texture2At(vec2(texCoord.x-amount, texCoord.y)).b\r\n\treturn vec4(clr, 1.0)\r\n}\r\n")
